"""Copilot harness: validate and evaluate in-memory ``.ax`` for semantic search / expert repair loops."""

from axiom.copilot.evaluator import evaluate_program, validate_program
from axiom.copilot.models import (
    EvaluationMode,
    ProgramCandidate,
    ProgramEvaluationReport,
    ProgramFailure,
    ProgramMetric,
    ProgramValidationReport,
    TrainTabularParams,
)
from axiom.copilot.artifacts import (
    COPILOT_ARTIFACT_SCHEMA_VERSION,
    build_iterations_document,
    build_search_report_document,
    evaluation_report_to_dict,
    expert_response_to_dict,
    persist_copilot_artifacts,
)
from axiom.copilot.search import (
    DEFAULT_METRIC_REPAIR_THRESHOLD,
    CopilotIterationRecord,
    CopilotSearchConfig,
    CopilotSearchResult,
    build_draft_context,
    build_repair_context,
    build_repair_error_report,
    format_failures_for_repair,
    format_metrics_for_repair,
    format_row_mismatches_for_repair,
    is_exact_symbolic_examples_task,
    merge_completion_overrides_into_context,
    run_copilot_search,
)
from axiom.copilot.benchmarks import (
    BENCHMARK_SUITE_SCHEMA_VERSION,
    DEFAULT_BENCHMARK_TASKS,
    BenchmarkDispatchExpert,
    BenchmarkRunRecord,
    BenchmarkSuiteResult,
    BenchmarkSummary,
    BenchmarkTask,
    benchmark_suite_to_dict,
    run_benchmark_draft_only,
    run_benchmark_search,
    run_benchmark_suite,
)
from axiom.copilot.summarize import (
    safe_summarize_evaluation,
    summary_context_from_report,
    trace_and_metrics_for_summary,
)

__all__ = [
    "BENCHMARK_SUITE_SCHEMA_VERSION",
    "BenchmarkDispatchExpert",
    "BenchmarkRunRecord",
    "BenchmarkSuiteResult",
    "BenchmarkSummary",
    "BenchmarkTask",
    "COPILOT_ARTIFACT_SCHEMA_VERSION",
    "DEFAULT_BENCHMARK_TASKS",
    "DEFAULT_METRIC_REPAIR_THRESHOLD",
    "CopilotIterationRecord",
    "CopilotSearchConfig",
    "CopilotSearchResult",
    "EvaluationMode",
    "ProgramCandidate",
    "ProgramEvaluationReport",
    "ProgramFailure",
    "ProgramMetric",
    "ProgramValidationReport",
    "TrainTabularParams",
    "build_draft_context",
    "build_iterations_document",
    "build_repair_context",
    "build_repair_error_report",
    "benchmark_suite_to_dict",
    "build_search_report_document",
    "evaluate_program",
    "evaluation_report_to_dict",
    "expert_response_to_dict",
    "format_failures_for_repair",
    "format_metrics_for_repair",
    "format_row_mismatches_for_repair",
    "is_exact_symbolic_examples_task",
    "merge_completion_overrides_into_context",
    "persist_copilot_artifacts",
    "run_benchmark_draft_only",
    "run_benchmark_search",
    "run_benchmark_suite",
    "run_copilot_search",
    "safe_summarize_evaluation",
    "summary_context_from_report",
    "trace_and_metrics_for_summary",
    "validate_program",
]
